version: "3.8"
services:
  device-sim-1:
    build: .
    environment:
      - DEVICE_ID=device-1
    volumes:
      - ./data:/data

  device-sim-2:
    build: .
    environment:
      - DEVICE_ID=device-2
    volumes:
      - ./data:/data

  device-sim-3:
    build: .
    environment:
      - DEVICE_ID=device-3
    volumes:
      - ./data:/data

  aggregator:
    image: python:3.12-slim
    volumes:
      - ./:/app         # montujemy cały projekt, by mieć aggregator.py
      - ./data:/data
    working_dir: /app
    command: ["python", "aggregator.py"]

networks:
  default:
    driver: bridge
